type: base_navigation
outputs: ["0","1","2","3","4","try again"]
tabs:
  "0": ["الرئيسية","الصفحة الرئيسية","اذهب للرئيسية","افتح الرئيسية"]
  "1": ["قارئ","ابدأ القراءة"]
  "2": ["السجل","المحفوظات","سجل القراءة"]
  "3": ["الاتصال","الاتصالات","الشبكة","وصل"]
  "4": ["الإعدادات","الخيارات","التفضيلات"]
unknown_reply: "اعد الكلام"
